/**
 * This file can be run using npm scripts too so i have not used ts here
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

function check() {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  // Load environment and environment schema file
  const envPath = path.join(__dirname, '../../.env');
  const schemaPath = path.join(__dirname, '../../env-schema.json');

  const envFile = fs.readFileSync(envPath, 'utf-8');
  const schemaFile = fs.readFileSync(schemaPath, 'utf-8');

  // Parse .env files into key-value pairs
  const envKeys = envFile
    .split('\n')
    .map((line) => line.split('=')[0].trim())
    .filter((key) => key && !key.startsWith('#'));

  // Parse json schema
  const schemaKeys = Object.keys(JSON.parse(schemaFile));

  // Find missing and extra keys
  const missingKeys = schemaKeys.filter((key) => !envKeys.includes(key));
  const extraKeys = envKeys.filter((key) => !schemaKeys.includes(key));

  if (missingKeys.length > 0) {
    console.log('\t🟥 Missing keys in environment file :', missingKeys);
  } else {
    console.log('\t🟩 No missing keys');
  }

  if (extraKeys.length > 0) {
    console.log('\t🟥 Extra keys in environment file:', extraKeys);
  } else {
    console.log('\t🟩 No extra keys');
  }

  return missingKeys;
}

function createEnv() {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  if (fs.existsSync(path.join(__dirname, '../../.env'))) {
    console.log('Environment file already exists checking for missing keys');
    const missingKeys = check();

    if (missingKeys.length) {
      const envPath = path.join(__dirname, '../../.env');

      const envFile = fs.readFileSync(envPath, 'utf-8');

      const schemaPath = path.join(__dirname, '../../env-schema.json');

      const schemaFile = fs.readFileSync(schemaPath, 'utf8');

      const schemaJSON = JSON.parse(schemaFile);

      const autoGeneratedText = '\n## AUTO GENERATED\n';
      const newEnvFileContent = missingKeys.map(
        (key) => `${key} = ${schemaJSON[key]?.example || ''}`,
      );

      const newEnvFile =
        envFile + autoGeneratedText + newEnvFileContent.join('\n') + '\n##';

      try {
        fs.writeFileSync(path.join(__dirname, '../../.env'), newEnvFile);
      } catch (err) {
        console.error('Error generating environment file', err);
      }
    }
  } else {
    try {
      const schemaPath = path.join(__dirname, '../../env-schema.json');

      const schemaFile = fs.readFileSync(schemaPath, 'utf8');

      const schemaJSON = JSON.parse(schemaFile);

      const schemaKeys = Object.keys(schemaJSON);

      const newEnv = schemaKeys.map(
        (key) => `${key} = ${schemaJSON[key]?.example || ''}`,
      );

      fs.writeFileSync(
        path.join(__dirname, '../../.env'),
        '## AUTO GENERATED\n\n' + newEnv.join('\n').toString() + '\n##',
      );
    } catch (err) {
      console.error(err);
    }
  }
}

const args = process.argv.slice(2);
console.log(args);

if (args[0] === 'gen_env') {
  createEnv();
}

const doctor = async (code = null) => {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);

  console.log('🟧 Running Tests');

  try {
    if (!fs.existsSync(path.join(__dirname, '../../.env'))) {
      console.error('🟥 Environment file missing');
    } else {
      console.log('🟩 Environment');
    }
  } catch (err) {
    console.error('Environment file not Found');
  }

  try {
    check();
  } catch (err) {
    console.error('Check Error');
  }
};

if (args[0] === 'doctor') {
  doctor();
}

export default doctor;
